autocode:
  transfer-restart: true
  root: E:\
  server: /server
  server-api: /api/v1/%s
  server-plug: /plugin/%s
  server-initialize: /initialize
  server-model: /model/%s
  server-request: /model/%s/request/
  server-router: /router/%s
  server-service: /service/%s
  web: /web/src
  web-api: /api
  web-form: /view
  web-table: /view
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
casbin:
  model-path: ./resource/rbac_model.conf
cors:
  mode: whitelist
  whitelist:
  - allow-origin: example1.com
    allow-methods: GET, POST
    allow-headers: content-type
    expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
      Content-Type
    allow-credentials: true
  - allow-origin: example2.com
    allow-methods: GET, POST
    allow-headers: content-type
    expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
      Content-Type
    allow-credentials: true
db-log-zap: false
db-list:
- disable: false
  conn-name: "default"
  path: 192.168.64.38
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: ""
  username: aroot
  password: "123456"
  max-idle-conns: 10
  max-open-conns: 100

- disable: false
  conn-name: "test"
  path: 192.168.64.38
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: ""
  username: aroot
  password: "123456"
  max-idle-conns: 10
  max-open-conns: 100

email:
  to: xxx@qq.com
  port: 465
  from: xxx@163.com
  host: smtp.163.com
  is-ssl: true
  secret: xxx
  nickname: test
excel:
  dir: ./resource/excel/
jwt:
  buffer-time: 86400
  expires-time: 86400
  issuer: qmPlus
  signing-key: 7a57d780-a977-4bf8-88eb-987558419553
local:
  path: uploads/file
redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""
system:
  env: public
  addr: 8888
  db-type: mysql
  oss-type: local
  use-multipoint: false
  use-redis: false
  iplimit-count: 15000
  iplimit-time: 3600
timer:
  start: true
  spec: '@daily'
  detail:
  - tableName: sys_operation_records
    compareField: created_at
    interval: 2160h
  - tableName: jwt_blacklists
    compareField: created_at
    interval: 168h
zap:
  level: info
  format: console
  prefix: '[Zap Log] '
  director: log
  show-line: true
  encode-level: CapitalColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
